/*
 * AppDynamics Cloud Query Service API
 *
 * An API providing access to observation data using an AppDynamics domain-specific language.  The language is declarative, read-only (it does not allow for data modification) and specific to the AppD MELT model. It presents MELT data (metrics, events, logs, traces) and State in the scope of monitored topology.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package querysvc

// A description of the schema of the data to follow in the DataResultChunks.
type Model struct {
	// This name will be used by the following DataResultChunks as a reference to the description of their structure.
	Name string `json:"name,omitempty"`
	// An array of type descriptors for each fetched expression in the query. The order of the array matches the order of values in the DataResultChunks with this schema model.'
	Fields []AnyOfModelFieldsItems `json:"fields,omitempty"`
}
