/*
 * AppDynamics Cloud Query Service API
 *
 * An API providing access to observation data using an AppDynamics domain-specific language.  The language is declarative, read-only (it does not allow for data modification) and specific to the AppD MELT model. It presents MELT data (metrics, events, logs, traces) and State in the scope of monitored topology.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package querysvc

// Additional information about a single fetched expression from the query.
type Hints struct {
	// Type of observed component from AppD MELT Model. Optional, if applicable
	Kind string `json:"kind,omitempty"`
	// Name of the MELT model property mentioned in the 'kind' hint. See AppD MELT Model  Optional, if applicable (for example not for expression)
	Field string `json:"field,omitempty"`
	// Full name with namespace of the type.
	Type_ string `json:"type,omitempty"`
}
