/*
 * AppDynamics Cloud Query Service API
 *
 * An API providing access to observation data using an AppDynamics domain-specific language.  The language is declarative, read-only (it does not allow for data modification) and specific to the AppD MELT model. It presents MELT data (metrics, events, logs, traces) and State in the scope of monitored topology.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package querysvc

// A detailed description of the error.
type ErrorDetailItem struct {
	// A short description on error cause.
	Message string `json:"message"`
	// A hint to resolve the error.
	FixSuggestion string `json:"fixSuggestion,omitempty"`
	// A list of fix possibilities to resolve the error.
	FixPossibilities []AnyOfErrorDetailItemFixPossibilitiesItems `json:"fixPossibilities"`
	// The type of the error.
	ErrorType string `json:"errorType"`
	// The start position of the error in format 'lineNum:charIdx'.
	ErrorFrom string `json:"errorFrom"`
	// The end position of the error in format 'lineNum:charIdx'.
	ErrorTo string `json:"errorTo"`
}
