/*
 * AppDynamics Cloud Connections API
 *
 * Enables you to manage cloud connections
 *
 * API version: 1.0.0
 * Contact: support@appdynamics.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AzureConfigurationDetails struct {
	Regions    *any                    `json:"regions,omitempty"`
	Polling    *ScheduleInterval       `json:"polling,omitempty"`
	ImportTags *ImportTagConfiguration `json:"importTags,omitempty"`
	TagFilter  string                  `json:"tagFilter,omitempty"`
	Services   *any                    `json:"services,omitempty"`
	// Azure Resource groups used to fetch metrics
	ResourceGroups []string `json:"resourceGroups,omitempty"`
}
