/*
 * AppDynamics Cloud Connections API
 *
 * Enables you to manage cloud connections
 *
 * API version: 1.0.0
 * Contact: support@appdynamics.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ConnectionAccessType : Connection type discriminator
type ConnectionAccessType string

// List of ConnectionAccessType
const (
	ROLE_DELEGATION_ConnectionAccessType ConnectionAccessType = "role_delegation"
	ACCESS_KEY_ConnectionAccessType ConnectionAccessType = "access_key"
)
