/*
 * AppDynamics Cloud Connections API
 *
 * Enables you to manage cloud connections
 *
 * API version: 1.0.0
 * Contact: support@appdynamics.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// How often the selected connection is polled for information
type ScheduleInterval struct {
	// The polling interval is five (5) minutes
	Interval int32 `json:"interval"`
	Unit string `json:"unit"`
}
