/*
 * AppDynamics Cloud Connections API
 *
 * Enables you to manage cloud connections
 *
 * API version: 1.0.0
 * Contact: support@appdynamics.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ProviderType : Provider type (also known as Connection type)
type ProviderType string

// List of ProviderType
const (
	AWS_ProviderType ProviderType = "aws"
	AZURE_ProviderType ProviderType = "azure"
)
