/*
 * AppDynamics Cloud Connections API
 *
 * Enables you to manage cloud connections
 *
 * API version: 1.0.0
 * Contact: support@appdynamics.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Configuration for importing tags of resources that are being monitored
type ImportTagConfiguration struct {
	// It is true by default. Tags will be imported for all the resources that are being monitored by default
	Enabled bool `json:"enabled"`
	// Array of that need to be excluded from being imported. It can be set only when enabled is true
	ExcludedKeys []string `json:"excludedKeys,omitempty"`
}
